version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
    restart: always
    networks:
      - backend

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - backend
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    image: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - backend

volumes:
  mariadb_data:
    driver_opts:
      type: bind
      device: /Users/eweiberl/data/database
      o: bind
  wordpress_data:
    driver_opts:
      type: bind
      device: /Users/eweiberl/data/wordpress
      o: bind

networks:
  backend:
    driver: bridge

# volumes:
#   mariadb_data:
#   wordpress_data:
