version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/sites-available/default:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    environment:
      NGINX_ENV_VAR: "${NGINX_ENV_VAR}"
    networks:
      - my-network

  wordpress:
    build:
      context: ./wordpress
    volumes:
      - wordpress-files:/var/www/html
      - wordpress-db:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    restart: always
    networks:
      - my-network

  db:
    build:
      context: ./mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  wordpress-db:
  wordpress-files:
  mariadb-data:
  certs:
