version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/default.conf:/etc/nginx/sites-available/default:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    depends_on:
      - wordpress
    networks:
      - my-network

  wordpress:
    build: ./wordpress
    volumes:
      - wordpress-files:/var/www/html
      - wordpress-db:/var/lib/mysql
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: example_db
    restart: always
    depends_on:
      - db
    networks:
      - my-network

  db:
    build: ./mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - wordpress-db:/var/lib/mysql
    restart: always
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  wordpress-db:
  wordpress-files:
  certs:
