version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    # volumes:
    #   - wordpress_data:/usr/share/nginx/html
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - wordpress
    restart: always
    networks:
      - backend

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    # volumes:
    #   - wordpress_data:/var/www/html/wordpress
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - backend
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: password
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mariadb_data:
  wordpress_data:
  # wordpress-db:
  # wordpress-files:
  # mariadb-data:
  # certs:
