version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always
    networks:
      - backend

  mariadb:
    build:
      context: ./mariadb
    container_name: mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  wordpress:
    build:
      context: ./wordpress
    container_name: wordpress
    image: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - backend
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
    driver_opts:
      type: none
      device: ${MARIADB_DEVICE}
      o: bind
  wordpress_data:
    driver_opts:
      type: none
      device: ${WORDPRESS_DEVICE}
      o: bind

networks:
  backend:
    driver: bridge
