CREATE USER '$DB_USER'@'$DB_HOST' IDENTIFIED BY '$WORDPRESS_USER_PASS';
CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$WORDPRESS_ADMIN_PASS';
FLUSH PRIVILEGES;